// SPDX-License-Identifier: AGPL-3.0
// Feel free to change the license, but this is what we use

// Feel free to change this version of Solidity. We support >=0.6.0 <0.7.0;
pragma solidity 0.6.12;
pragma experimental ABIEncoderV2;

// These are the core Yearn libraries
import {BaseStrategy, StrategyParams} from "@yearnvaults/contracts/BaseStrategy.sol";
import {SafeERC20, SafeMath, IERC20, Address} from "@openzeppelin/contracts/token/ERC20/SafeERC20.sol";
import "../interfaces/keeperDao.sol";
import "../interfaces/uniswap.sol";

// Import interfaces for many popular DeFi projects, or add your own!
//import "../interfaces/<protocol>/<Interface>.sol";

contract Strategy is BaseStrategy {
    using SafeERC20 for IERC20;
    using Address for address;
    using SafeMath for uint256;

    IDistributeV1 private distributor = IDistributeV1(address(0xcadF6735144D1d7f1A875a5561555cBa5df2f75C));
    IUniswapV2Router02 private uniswapRouter = IUniswapV2Router02(address(0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D));
    ILiquidityPool public pool = ILiquidityPool(address(0x35fFd6E268610E764fF6944d07760D0EFe5E40E5));
    IERC20 public rook = IERC20(address(0xfA5047c9c78B8877af97BDcb85Db743fD7313d4a));

    IKToken public kToken;

    address[2] public path;

    constructor(address _vault) public BaseStrategy(_vault) {
        // You can set these parameters on deployment to whatever you want
        // maxReportDelay = 6300;
        // profitFactor = 100;
        // debtThreshold = 0;

        // check to see if KeeperDao can actually accept want (BTC, DAI, USDC, ETH, WETH)
        kToken = pool.kToken(want);
        require(address(_kToken) != address(0x0), "Protocol doesn't support this token!");

        want.safeApprove(address(pool), uint256(- 1));
        rook.safeApprove(address(this), uint256(- 1));

        path = [address(rook), address(want)];

    }

    function name() external view override returns (string memory) {
        // Add your own name here, suggestion e.g. "StrategyCreamYFI"
        return 'StrategyKeeperDAOGenericSingle';
    }

    function estimatedTotalAssets() public view override returns (uint256) {
        return balanceOfStaked().add(balanceOfUnstaked()).add(_estimateReward(balanceOfReward()));
    }

    function balanceOfUnstaked() public view returns (uint256){
        return want.balanceOf(address(this));
    }

    function balanceOfStaked() public view returns (uint256){
        return kToken.balanceOf(address(this));
    }

    function balanceOfReward() public view returns (uint256){
        return rook.balanceOf(address(this));
    }

    function prepareReturn(uint256 _debtOutstanding) internal override returns (
        uint256 _profit,
        uint256 _loss,
        uint256 _debtPayment
    )
    {
        // TODO: Do stuff here to free up any returns back into `want`
        // NOTE: Return `_profit` which is value generated by all positions, priced in `want`
        // NOTE: Should try to free up at least `_debtOutstanding` of underlying position

        return (_profit, _loss, _debtPayment);
    }

    function adjustPosition(uint256 _debtOutstanding) internal override {
        // NOTE: Try to adjust positions so that `_debtOutstanding` can be freed up on *next* harvest (not immediately)

        pool.deposit(address(kToken), balanceOfUnstaked());
    }

    function liquidatePosition(uint256 _amountNeeded) internal override returns (uint256 _liquidatedAmount, uint256 _loss) {
        // NOTE: Maintain invariant `want.balanceOf(this) >= _liquidatedAmount`
        // NOTE: Maintain invariant `_liquidatedAmount + _loss <= _amountNeeded`
        
        uint256 rewards = balanceOfReward();
        if (rewards > 0) {
            _sell(rewards);
        }

        // if _amountNeeded is more than currently available, need to unstake some and/or sell rewards to free up assets
        if (_amountNeeded > balanceOfUnstaked()) {
            uint256 desiredWithdrawAmount = _amountNeeded.sub(balanceOfUnstaked());

            // can't withdraw more than staked
            uint256 actualWithdrawAmount = Math.min(desiredWithdrawAmount, balanceOfStaked());
            pool.withdraw(address(this), address(kToken), actualWithdrawAmount);

            _liquidatedAmount = balanceOfUnstaked();
            // already withdrew all that it could, any difference left is considered _loss,
            // which is possible because of KeeperDao's initial deposit NAV premium of 0.64%
            // i.e initial 10,000 deposit -> 9,936 in pool. If withdraw immediately, _loss = 64
            _loss = _amountNeeded.sub(_liquidatedAmount);

        } else {
            // already have all of _amountNeeded unstaked
            _liquidatedAmount = _amountNeeded;
            _loss = 0;
        }

        return (_liquidatedAmount, _loss);
    }

    // NOTE: Can override `tendTrigger` and `harvestTrigger` if necessary
    function prepareMigration(address _newStrategy) internal override {
        kToken.transfer(_newStrategy, balanceOfStaked());
        rook.transfer(_newStrategy, balanceOfReward());
    }

    // require off-chain data. Claim externally
    function _redeemRewards(address _to, uint256 _earningsToDate, uint256 _nonce, bytes memory _signature) external {
        distributor.claim(_to, _earningsToDate, _nonce, _signature);
    }

    function _sell(uint256 _amount) internal {
        uniswapRouter.swapExactTokensForTokens(_amount, uint256(0), path, address(this), now);
    }

    function _estimateReward(uint256 _amount) internal returns (uint256){
        return uniswapRouter.getAmountsOut(_amount, path);
    }

    function protectedTokens()
    internal
    view
    override
    returns (address[] memory)
    {
        address[] memory protected = new address[](1);
        protected[0] = kToken;
        protected[1] = rook;
        return protected;
    }
}
